@AquilaTodos_HostAddress = https://localhost:7044
@ListId = 1
@city = London

GET {{AquilaTodos_HostAddress}}/api/TodoList
Accept: application/json

###


GET {{AquilaTodos_HostAddress}}/api/TodoList/{{ListId}}/Item
Accept: application/json

###

GET {{AquilaTodos_HostAddress}}/api/Weather/{{city}}
Accept: application/json
